on:
  push:
    branches:
      - 'main'

permissions:
      id-token: write
      contents: read

jobs: 
  provision-westeurope:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.0'

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}          
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}   

    - name: Terraform Init
      run: terraform init
      working-directory: ./iac

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./iac

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./iac

    - name: Upload HTML to App Service
      run: |
        az webapp deployment source config-zip \
          --resource-group projectrg \
          --name projectcobra \
          --src-path ./index.html
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}